version: "3.8"
services:
  backend:
    build: ./backend
    image: reyhanacynthia/yolo-backend:v1.0.1
    container_name: yolo-backend
    ports:
      - "5001:5000"
    depends_on:
      - "mongodb"
    networks:
      - yolo-network
    stdin_open: true
    tty: true

  client:
    build: ./client
    image: reyhanacynthia/yolo-client:v1.0.1
    container_name: yolo-client
    ports:
      - "3000:3000"
    links:
      - "backend"
    networks:
      - yolo-network
    stdin_open: true
    tty: true

  mongodb-service:
    image: mongo
    container_name: yolo-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - yolo-network

volumes:
  mongodb_data:

networks:
  yolo-network:
    driver: bridge
