---
- name: Check if yolo web application is already cloned
  stat:
    path: "{{ chdir }}"
  register: yolo_repo_status

- name: Clone yolo web application from GitHub
  git:
    repo: https://github.com/cynthia7125/yolo
    dest: "{{ chdir }}"
  when: not yolo_repo_status.stat.exists
  tags:
    - clone