---
- block:
    - name: Update package lists
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install python
      apt:
        name: python3-pip
        state: present
      tags:
        - docker

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags:
        - docker

    - name: Install Docker Compose using pip
      pip:
        name: docker-compose
        executable: pip3
        state: latest
      become: true

    - name: Run docker-compose up
      command: docker-compose up -d
      args:
        chdir: /vagrant
      tags: 
        - docker-compose
      
  rescue:
    - name: Handle Docker installation errors
      debug:
        msg: "Error occurred while installing Docker."